server:
  port: 8085

spring:
  application:
    name: geospatial-service

  data:
    redis:
      host:
      port:
  kafka:
    bootstrap-servers: 192.168.1.100:9092
    producer:
      acks: 1
      delivery-timeout-ms: 60000
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.add.type.headers: true
        linger.ms: 50 # 메시지를 모아서 보내는 시간
        batch.size: 131072 # 128KB
        buffer.memory: 33554432 # 32MB
        request.timeout.ms: 30000
    consumer:
      group-id: geospatial-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: true
        spring.json.trusted.packages: "*"
        max.poll.records: 500
        spring.json.type.mapping: >
          com.example.trip_service.kafka.dto.TripMatchedEvent:com.example.geospatial_service.kafka.dto.TripMatchedEvent,
          com.example.trip_service.kafka.dto.TripCompletedEvent:com.example.geospatial_service.kafka.dto.TripCompletedEvent
    listener:
      ack-mode: RECORD

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka