server:
  port: 8085
  shutdown: graceful

spring:
  application:
    name: geospatial-service
  lifecycle:
    timeout-per-shutdown-phase: 30s

  redis:
    cache:
      host: ${SPRING_REDIS_CACHE_HOST:localhost}
      port: ${SPRING_REDIS_CACHE_PORT:6379}
    storage:
      host: ${SPRING_REDIS_STORAGE_HOST:localhost}
      port: ${SPRING_REDIS_STORAGE_PORT:6380}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: 1
      delivery-timeout-ms: 60000
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.add.type.headers: true
        delivery.timeout.ms: 120000
        linger.ms: 10
        batch.size: 130000
        compression-type: zstd # 압축
        request.timeout.ms: 30000
    consumer:
      group-id: geospatial-service-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.use.type.headers: true
        spring.json.trusted.packages: "*"
        max.poll.records: 500
        spring.json.type.mapping: >
          com.example.trip_service.kafka.dto.TripMatchedEvent:com.example.geospatial_service.kafka.dto.TripMatchedEvent,
          com.example.trip_service.kafka.dto.TripCompletedEvent:com.example.geospatial_service.kafka.dto.TripCompletedEvent,
          com.example.trip_service.kafka.dto.TripCanceledEvent:com.example.geospatial_service.kafka.dto.TripCanceledEvent

    template:
      observation-enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}"

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

  endpoints:
    web:
      exposure:
        include: "health, prometheus"

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: "${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}"