server:
  port: 8085

spring:
  application:
    name: geospatial-service

  redis:
    cache:
      host: localhost
      port: 6379
    storage:
      host: localhost
      port: 6380

  kafka:
    bootstrap-servers: 192.168.1.100:9092
    producer:
      acks: 1
      delivery-timeout-ms: 60000
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.add.type.headers: true
        linger.ms: 50
        batch.size: 131072
        buffer.memory: 33554432
        request.timeout.ms: 30000
    consumer:
      group-id: geospatial-service-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.use.type.headers: true
        spring.json.trusted.packages: "*"
        max.poll.records: 500
        spring.json.type.mapping: >
          com.example.trip_service.kafka.dto.TripMatchedEvent:com.example.geospatial_service.kafka.dto.TripMatchedEvent,
          com.example.trip_service.kafka.dto.TripCompletedEvent:com.example.geospatial_service.kafka.dto.TripCompletedEvent,
          com.example.trip_service.kafka.dto.TripCanceledEvent:com.example.geospatial_service.kafka.dto.TripCanceledEvent
    listener:
      ack-mode: BATCH
      observation-enabled: true
    template:
      observation-enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      tracing:
        endpoint: "http://localhost:9411/api/v2/spans"